apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zlakes.mock.digi.dev
spec:
  group: mock.digi.dev
  names:
    kind: Zlake
    listKind: ZlakeList
    plural: zlakes
    singular: zlake
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              data:
                properties:
                  input:
                    properties:
                      format:
                        type: string
                      location:
                        type: string
                      zql:
                        type: string
                    type: object
                  output:
                    properties:
                      format:
                        type: string
                      location:
                        type: string
                    type: object
                type: object
              obs:
                properties:
                  reason:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
