kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imitator
subjects:
- kind: ServiceAccount
  name: imitator
roleRef:
  kind: Role
  name: imitator
  apiGroup: rbac.authorization.k8s.io
