kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: policer
subjects:
- kind: ServiceAccount
  name: policer
roleRef:
  kind: Role
  name: policer
  apiGroup: rbac.authorization.k8s.io
