apiVersion: bench.digi.dev/v1
kind: Lamp
metadata:
  name: {{ .Values.name }}
spec:
  control:
    power:
      intent: "on"
    brightness:
      intent: 0.8
  meta:
    forward_value: 0.1
    backward_value: 0.1
    endpoint: d0:73:d5:5b:bb:fd
    poll_interval: 0.1
    discover_retry: 3
