apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rooms.mock.digi.dev
spec:
  group: mock.digi.dev
  names:
    kind: Room
    listKind: RoomList
    plural: rooms
    singular: room
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Room is the Schema for the rooms API
        properties:
          apiVersion:
            description: ''
            type: string
          kind:
            description: ''
            type: string
          metadata:
            type: object
          spec:
            properties:
              control:
                properties:
                  brightness:
                    properties:
                      intent:
                        type: number
                      status:
                        type: number
                    type: object
                  mode:
                    properties:
                      intent:
                        type: string
                      status:
                        type: string
                    type: object
                type: object
              mount:
                properties:
                  mock.digi.dev/v1/lamps:
                    additionalProperties:
                      properties:
                        mode:
                          type: string
                        spec:
                          description: Schema of the lamp model
                          properties:
                            control:
                              properties:
                                brightness:
                                  properties:
                                    intent:
                                      type: number
                                    status:
                                      type: number
                                  type: object
                                power:
                                  properties:
                                    intent:
                                      type: string
                                    status:
                                      type: string
                                  type: object
                              type: object
                            obs:
                              properties:
                                reason:
                                  type: string
                              type: object
                          type: object
                        status:
                          type: string
                      type: object
                    type: object
                type: object
              obs:
                properties:
                  objects:
                    items:
                      additionalProperties:
                        properties:
                          h:
                            type: number
                          w:
                            type: number
                          x:
                            type: number
                          y:
                            type: number
                        type: object
                      type: object
                    type: array
                  reason:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
