apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imitates.digi.dev
spec:
  scope: Namespaced
  group: digi.dev
  names:
    kind: Imitate
    plural: imitates
    singular: imitate
    shortNames:
      - imts
      - imt
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: Imitate is the Schema for the imitate API
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                strategy:
                  type: string
                obs:
                  type: array
                  items:
                    type: string
                action:
                  type: array
                  items:
                    type: string
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.update_imt.message
          description: As returned from the handler (sometimes).
