apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mountpolicies.digi.dev
spec:
  group: digi.dev
  names:
    kind: MountPolicy
    listKind: MountPolicyList
    plural: mountpolicies
    singular: mountpolicy
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: MountPolicy is the Schema for the mountpolicies API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MountPolicySpec defines the mount policies.
            properties:
              action:
                type: string
              condition:
                type: string
              source:
                description: Auri identifies a set of attributes belonging to a model
                  on the semantic message bus E.g., /digi.dev/v1/Roomba/default/roomba-foo.power
                properties:
                  kind:
                    description: model schema
                    properties:
                      group:
                        description: Model schema group
                        type: string
                      name:
                        description: Schema name; first letter capitalized, e.g.,
                          Roomba
                        type: string
                      version:
                        description: Schema version
                        type: string
                    type: object
                  name:
                    description: name of the model
                    type: string
                  namespace:
                    description: namespace of the model
                    type: string
                  path:
                    description: path to attribute(s) in the model; if path empty,
                      Auri points to the model
                    type: string
                type: object
              target:
                description: Auri identifies a set of attributes belonging to a model
                  on the semantic message bus E.g., /digi.dev/v1/Roomba/default/roomba-foo.power
                properties:
                  kind:
                    description: model schema
                    properties:
                      group:
                        description: Model schema group
                        type: string
                      name:
                        description: Schema name; first letter capitalized, e.g.,
                          Roomba
                        type: string
                      version:
                        description: Schema version
                        type: string
                    type: object
                  name:
                    description: name of the model
                    type: string
                  namespace:
                    description: namespace of the model
                    type: string
                  path:
                    description: path to attribute(s) in the model; if path empty,
                      Auri points to the model
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
