apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: lamps.digi.dev
spec:
  group: mock.digi.dev
  names:
    kind: Lamp
    listKind: LampList
    plural: lamps
    singular: lamp
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Lamp is the Schema for the lamps API
        properties:
          apiVersion:
            description: ''
            type: string
          kind:
            description: ''
            type: string
          metadata:
            type: object
          spec:
            description: Schema of the lamp model
            properties:
              control:
                properties:
                  brightness:
                    properties:
                      intent:
                        type: number
                      status:
                        type: number
                    type: object
                  power:
                    properties:
                      intent:
                        type: string
                      status:
                        type: string
                    type: object
                type: object
              obs:
                properties:
                  reason:
                    type: string
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
